/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MarisIT.Api.Client.OpenAPIDateConverter;

namespace MarisIT.Api.Model
{
    /// <summary>
    /// TransunionCommercialPolicyRiskAddressIA
    /// </summary>
    [DataContract]
    public partial class TransunionCommercialPolicyRiskAddressIA :  IEquatable<TransunionCommercialPolicyRiskAddressIA>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransunionCommercialPolicyRiskAddressIA" /> class.
        /// </summary>
        /// <param name="productCode">productCode.</param>
        /// <param name="policyCounter">policyCounter.</param>
        /// <param name="riskAddress1">riskAddress1.</param>
        /// <param name="riskAddress2">riskAddress2.</param>
        /// <param name="riskAddress3">riskAddress3.</param>
        /// <param name="riskAddress4">riskAddress4.</param>
        /// <param name="riskPostalCode">riskPostalCode.</param>
        public TransunionCommercialPolicyRiskAddressIA(string productCode = default(string), string policyCounter = default(string), string riskAddress1 = default(string), string riskAddress2 = default(string), string riskAddress3 = default(string), string riskAddress4 = default(string), string riskPostalCode = default(string))
        {
            this.ProductCode = productCode;
            this.PolicyCounter = policyCounter;
            this.RiskAddress1 = riskAddress1;
            this.RiskAddress2 = riskAddress2;
            this.RiskAddress3 = riskAddress3;
            this.RiskAddress4 = riskAddress4;
            this.RiskPostalCode = riskPostalCode;
            this.ProductCode = productCode;
            this.PolicyCounter = policyCounter;
            this.RiskAddress1 = riskAddress1;
            this.RiskAddress2 = riskAddress2;
            this.RiskAddress3 = riskAddress3;
            this.RiskAddress4 = riskAddress4;
            this.RiskPostalCode = riskPostalCode;
        }

        /// <summary>
        /// Gets or Sets ProductCode
        /// </summary>
        [DataMember(Name="productCode", EmitDefaultValue=true)]
        public string ProductCode { get; set; }

        /// <summary>
        /// Gets or Sets PolicyCounter
        /// </summary>
        [DataMember(Name="policyCounter", EmitDefaultValue=true)]
        public string PolicyCounter { get; set; }

        /// <summary>
        /// Gets or Sets RiskAddress1
        /// </summary>
        [DataMember(Name="riskAddress1", EmitDefaultValue=true)]
        public string RiskAddress1 { get; set; }

        /// <summary>
        /// Gets or Sets RiskAddress2
        /// </summary>
        [DataMember(Name="riskAddress2", EmitDefaultValue=true)]
        public string RiskAddress2 { get; set; }

        /// <summary>
        /// Gets or Sets RiskAddress3
        /// </summary>
        [DataMember(Name="riskAddress3", EmitDefaultValue=true)]
        public string RiskAddress3 { get; set; }

        /// <summary>
        /// Gets or Sets RiskAddress4
        /// </summary>
        [DataMember(Name="riskAddress4", EmitDefaultValue=true)]
        public string RiskAddress4 { get; set; }

        /// <summary>
        /// Gets or Sets RiskPostalCode
        /// </summary>
        [DataMember(Name="riskPostalCode", EmitDefaultValue=true)]
        public string RiskPostalCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransunionCommercialPolicyRiskAddressIA {\n");
            sb.Append("  ProductCode: ").Append(ProductCode).Append("\n");
            sb.Append("  PolicyCounter: ").Append(PolicyCounter).Append("\n");
            sb.Append("  RiskAddress1: ").Append(RiskAddress1).Append("\n");
            sb.Append("  RiskAddress2: ").Append(RiskAddress2).Append("\n");
            sb.Append("  RiskAddress3: ").Append(RiskAddress3).Append("\n");
            sb.Append("  RiskAddress4: ").Append(RiskAddress4).Append("\n");
            sb.Append("  RiskPostalCode: ").Append(RiskPostalCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransunionCommercialPolicyRiskAddressIA);
        }

        /// <summary>
        /// Returns true if TransunionCommercialPolicyRiskAddressIA instances are equal
        /// </summary>
        /// <param name="input">Instance of TransunionCommercialPolicyRiskAddressIA to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransunionCommercialPolicyRiskAddressIA input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ProductCode == input.ProductCode ||
                    (this.ProductCode != null &&
                    this.ProductCode.Equals(input.ProductCode))
                ) && 
                (
                    this.PolicyCounter == input.PolicyCounter ||
                    (this.PolicyCounter != null &&
                    this.PolicyCounter.Equals(input.PolicyCounter))
                ) && 
                (
                    this.RiskAddress1 == input.RiskAddress1 ||
                    (this.RiskAddress1 != null &&
                    this.RiskAddress1.Equals(input.RiskAddress1))
                ) && 
                (
                    this.RiskAddress2 == input.RiskAddress2 ||
                    (this.RiskAddress2 != null &&
                    this.RiskAddress2.Equals(input.RiskAddress2))
                ) && 
                (
                    this.RiskAddress3 == input.RiskAddress3 ||
                    (this.RiskAddress3 != null &&
                    this.RiskAddress3.Equals(input.RiskAddress3))
                ) && 
                (
                    this.RiskAddress4 == input.RiskAddress4 ||
                    (this.RiskAddress4 != null &&
                    this.RiskAddress4.Equals(input.RiskAddress4))
                ) && 
                (
                    this.RiskPostalCode == input.RiskPostalCode ||
                    (this.RiskPostalCode != null &&
                    this.RiskPostalCode.Equals(input.RiskPostalCode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ProductCode != null)
                    hashCode = hashCode * 59 + this.ProductCode.GetHashCode();
                if (this.PolicyCounter != null)
                    hashCode = hashCode * 59 + this.PolicyCounter.GetHashCode();
                if (this.RiskAddress1 != null)
                    hashCode = hashCode * 59 + this.RiskAddress1.GetHashCode();
                if (this.RiskAddress2 != null)
                    hashCode = hashCode * 59 + this.RiskAddress2.GetHashCode();
                if (this.RiskAddress3 != null)
                    hashCode = hashCode * 59 + this.RiskAddress3.GetHashCode();
                if (this.RiskAddress4 != null)
                    hashCode = hashCode * 59 + this.RiskAddress4.GetHashCode();
                if (this.RiskPostalCode != null)
                    hashCode = hashCode * 59 + this.RiskPostalCode.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
