/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MarisIT.Api.Client.OpenAPIDateConverter;

namespace MarisIT.Api.Model
{
    /// <summary>
    /// TransunionConsumer118InsuranceClaimsUI01
    /// </summary>
    [DataContract]
    public partial class TransunionConsumer118InsuranceClaimsUI01 :  IEquatable<TransunionConsumer118InsuranceClaimsUI01>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransunionConsumer118InsuranceClaimsUI01" /> class.
        /// </summary>
        /// <param name="claims">claims.</param>
        public TransunionConsumer118InsuranceClaimsUI01(List<TransunionConsumer118Claim> claims = default(List<TransunionConsumer118Claim>))
        {
            this.Claims = claims;
            this.Claims = claims;
        }

        /// <summary>
        /// Gets or Sets Claims
        /// </summary>
        [DataMember(Name="claims", EmitDefaultValue=true)]
        public List<TransunionConsumer118Claim> Claims { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransunionConsumer118InsuranceClaimsUI01 {\n");
            sb.Append("  Claims: ").Append(Claims).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransunionConsumer118InsuranceClaimsUI01);
        }

        /// <summary>
        /// Returns true if TransunionConsumer118InsuranceClaimsUI01 instances are equal
        /// </summary>
        /// <param name="input">Instance of TransunionConsumer118InsuranceClaimsUI01 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransunionConsumer118InsuranceClaimsUI01 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Claims == input.Claims ||
                    this.Claims != null &&
                    input.Claims != null &&
                    this.Claims.SequenceEqual(input.Claims)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Claims != null)
                    hashCode = hashCode * 59 + this.Claims.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
