/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MarisIT.Api.Client.OpenAPIDateConverter;

namespace MarisIT.Api.Model
{
    /// <summary>
    /// TransunionConsumer118LinkagesLK
    /// </summary>
    [DataContract]
    public partial class TransunionConsumer118LinkagesLK :  IEquatable<TransunionConsumer118LinkagesLK>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransunionConsumer118LinkagesLK" /> class.
        /// </summary>
        /// <param name="iLinkSurnameO">iLinkSurnameO.</param>
        /// <param name="iLinkForenameO">iLinkForenameO.</param>
        /// <param name="iLinkCell">iLinkCell.</param>
        /// <param name="iLinkHomeTelephone">iLinkHomeTelephone.</param>
        /// <param name="iLinkWorkTelephone">iLinkWorkTelephone.</param>
        /// <param name="iLinkAddress">iLinkAddress.</param>
        /// <param name="iAddressLine1">iAddressLine1.</param>
        /// <param name="iAddressLine2">iAddressLine2.</param>
        /// <param name="iAddressSuburb">iAddressSuburb.</param>
        /// <param name="iAddressTown">iAddressTown.</param>
        /// <param name="iAddressCode">iAddressCode.</param>
        /// <param name="iLinkArrayList">iLinkArrayList.</param>
        public TransunionConsumer118LinkagesLK(string iLinkSurnameO = default(string), string iLinkForenameO = default(string), string iLinkCell = default(string), string iLinkHomeTelephone = default(string), string iLinkWorkTelephone = default(string), string iLinkAddress = default(string), string iAddressLine1 = default(string), string iAddressLine2 = default(string), string iAddressSuburb = default(string), string iAddressTown = default(string), string iAddressCode = default(string), List<TransunionConsumer118ILinkArray> iLinkArrayList = default(List<TransunionConsumer118ILinkArray>))
        {
            this.ILinkSurnameO = iLinkSurnameO;
            this.ILinkForenameO = iLinkForenameO;
            this.ILinkCell = iLinkCell;
            this.ILinkHomeTelephone = iLinkHomeTelephone;
            this.ILinkWorkTelephone = iLinkWorkTelephone;
            this.ILinkAddress = iLinkAddress;
            this.IAddressLine1 = iAddressLine1;
            this.IAddressLine2 = iAddressLine2;
            this.IAddressSuburb = iAddressSuburb;
            this.IAddressTown = iAddressTown;
            this.IAddressCode = iAddressCode;
            this.ILinkArrayList = iLinkArrayList;
            this.ILinkSurnameO = iLinkSurnameO;
            this.ILinkForenameO = iLinkForenameO;
            this.ILinkCell = iLinkCell;
            this.ILinkHomeTelephone = iLinkHomeTelephone;
            this.ILinkWorkTelephone = iLinkWorkTelephone;
            this.ILinkAddress = iLinkAddress;
            this.IAddressLine1 = iAddressLine1;
            this.IAddressLine2 = iAddressLine2;
            this.IAddressSuburb = iAddressSuburb;
            this.IAddressTown = iAddressTown;
            this.IAddressCode = iAddressCode;
            this.ILinkArrayList = iLinkArrayList;
        }

        /// <summary>
        /// Gets or Sets ILinkSurnameO
        /// </summary>
        [DataMember(Name="iLinkSurnameO", EmitDefaultValue=true)]
        public string ILinkSurnameO { get; set; }

        /// <summary>
        /// Gets or Sets ILinkForenameO
        /// </summary>
        [DataMember(Name="iLinkForenameO", EmitDefaultValue=true)]
        public string ILinkForenameO { get; set; }

        /// <summary>
        /// Gets or Sets ILinkCell
        /// </summary>
        [DataMember(Name="iLinkCell", EmitDefaultValue=true)]
        public string ILinkCell { get; set; }

        /// <summary>
        /// Gets or Sets ILinkHomeTelephone
        /// </summary>
        [DataMember(Name="iLinkHomeTelephone", EmitDefaultValue=true)]
        public string ILinkHomeTelephone { get; set; }

        /// <summary>
        /// Gets or Sets ILinkWorkTelephone
        /// </summary>
        [DataMember(Name="iLinkWorkTelephone", EmitDefaultValue=true)]
        public string ILinkWorkTelephone { get; set; }

        /// <summary>
        /// Gets or Sets ILinkAddress
        /// </summary>
        [DataMember(Name="iLinkAddress", EmitDefaultValue=true)]
        public string ILinkAddress { get; set; }

        /// <summary>
        /// Gets or Sets IAddressLine1
        /// </summary>
        [DataMember(Name="iAddressLine1", EmitDefaultValue=true)]
        public string IAddressLine1 { get; set; }

        /// <summary>
        /// Gets or Sets IAddressLine2
        /// </summary>
        [DataMember(Name="iAddressLine2", EmitDefaultValue=true)]
        public string IAddressLine2 { get; set; }

        /// <summary>
        /// Gets or Sets IAddressSuburb
        /// </summary>
        [DataMember(Name="iAddressSuburb", EmitDefaultValue=true)]
        public string IAddressSuburb { get; set; }

        /// <summary>
        /// Gets or Sets IAddressTown
        /// </summary>
        [DataMember(Name="iAddressTown", EmitDefaultValue=true)]
        public string IAddressTown { get; set; }

        /// <summary>
        /// Gets or Sets IAddressCode
        /// </summary>
        [DataMember(Name="iAddressCode", EmitDefaultValue=true)]
        public string IAddressCode { get; set; }

        /// <summary>
        /// Gets or Sets ILinkArrayList
        /// </summary>
        [DataMember(Name="iLinkArrayList", EmitDefaultValue=true)]
        public List<TransunionConsumer118ILinkArray> ILinkArrayList { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransunionConsumer118LinkagesLK {\n");
            sb.Append("  ILinkSurnameO: ").Append(ILinkSurnameO).Append("\n");
            sb.Append("  ILinkForenameO: ").Append(ILinkForenameO).Append("\n");
            sb.Append("  ILinkCell: ").Append(ILinkCell).Append("\n");
            sb.Append("  ILinkHomeTelephone: ").Append(ILinkHomeTelephone).Append("\n");
            sb.Append("  ILinkWorkTelephone: ").Append(ILinkWorkTelephone).Append("\n");
            sb.Append("  ILinkAddress: ").Append(ILinkAddress).Append("\n");
            sb.Append("  IAddressLine1: ").Append(IAddressLine1).Append("\n");
            sb.Append("  IAddressLine2: ").Append(IAddressLine2).Append("\n");
            sb.Append("  IAddressSuburb: ").Append(IAddressSuburb).Append("\n");
            sb.Append("  IAddressTown: ").Append(IAddressTown).Append("\n");
            sb.Append("  IAddressCode: ").Append(IAddressCode).Append("\n");
            sb.Append("  ILinkArrayList: ").Append(ILinkArrayList).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransunionConsumer118LinkagesLK);
        }

        /// <summary>
        /// Returns true if TransunionConsumer118LinkagesLK instances are equal
        /// </summary>
        /// <param name="input">Instance of TransunionConsumer118LinkagesLK to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransunionConsumer118LinkagesLK input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ILinkSurnameO == input.ILinkSurnameO ||
                    (this.ILinkSurnameO != null &&
                    this.ILinkSurnameO.Equals(input.ILinkSurnameO))
                ) && 
                (
                    this.ILinkForenameO == input.ILinkForenameO ||
                    (this.ILinkForenameO != null &&
                    this.ILinkForenameO.Equals(input.ILinkForenameO))
                ) && 
                (
                    this.ILinkCell == input.ILinkCell ||
                    (this.ILinkCell != null &&
                    this.ILinkCell.Equals(input.ILinkCell))
                ) && 
                (
                    this.ILinkHomeTelephone == input.ILinkHomeTelephone ||
                    (this.ILinkHomeTelephone != null &&
                    this.ILinkHomeTelephone.Equals(input.ILinkHomeTelephone))
                ) && 
                (
                    this.ILinkWorkTelephone == input.ILinkWorkTelephone ||
                    (this.ILinkWorkTelephone != null &&
                    this.ILinkWorkTelephone.Equals(input.ILinkWorkTelephone))
                ) && 
                (
                    this.ILinkAddress == input.ILinkAddress ||
                    (this.ILinkAddress != null &&
                    this.ILinkAddress.Equals(input.ILinkAddress))
                ) && 
                (
                    this.IAddressLine1 == input.IAddressLine1 ||
                    (this.IAddressLine1 != null &&
                    this.IAddressLine1.Equals(input.IAddressLine1))
                ) && 
                (
                    this.IAddressLine2 == input.IAddressLine2 ||
                    (this.IAddressLine2 != null &&
                    this.IAddressLine2.Equals(input.IAddressLine2))
                ) && 
                (
                    this.IAddressSuburb == input.IAddressSuburb ||
                    (this.IAddressSuburb != null &&
                    this.IAddressSuburb.Equals(input.IAddressSuburb))
                ) && 
                (
                    this.IAddressTown == input.IAddressTown ||
                    (this.IAddressTown != null &&
                    this.IAddressTown.Equals(input.IAddressTown))
                ) && 
                (
                    this.IAddressCode == input.IAddressCode ||
                    (this.IAddressCode != null &&
                    this.IAddressCode.Equals(input.IAddressCode))
                ) && 
                (
                    this.ILinkArrayList == input.ILinkArrayList ||
                    this.ILinkArrayList != null &&
                    input.ILinkArrayList != null &&
                    this.ILinkArrayList.SequenceEqual(input.ILinkArrayList)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ILinkSurnameO != null)
                    hashCode = hashCode * 59 + this.ILinkSurnameO.GetHashCode();
                if (this.ILinkForenameO != null)
                    hashCode = hashCode * 59 + this.ILinkForenameO.GetHashCode();
                if (this.ILinkCell != null)
                    hashCode = hashCode * 59 + this.ILinkCell.GetHashCode();
                if (this.ILinkHomeTelephone != null)
                    hashCode = hashCode * 59 + this.ILinkHomeTelephone.GetHashCode();
                if (this.ILinkWorkTelephone != null)
                    hashCode = hashCode * 59 + this.ILinkWorkTelephone.GetHashCode();
                if (this.ILinkAddress != null)
                    hashCode = hashCode * 59 + this.ILinkAddress.GetHashCode();
                if (this.IAddressLine1 != null)
                    hashCode = hashCode * 59 + this.IAddressLine1.GetHashCode();
                if (this.IAddressLine2 != null)
                    hashCode = hashCode * 59 + this.IAddressLine2.GetHashCode();
                if (this.IAddressSuburb != null)
                    hashCode = hashCode * 59 + this.IAddressSuburb.GetHashCode();
                if (this.IAddressTown != null)
                    hashCode = hashCode * 59 + this.IAddressTown.GetHashCode();
                if (this.IAddressCode != null)
                    hashCode = hashCode * 59 + this.IAddressCode.GetHashCode();
                if (this.ILinkArrayList != null)
                    hashCode = hashCode * 59 + this.ILinkArrayList.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
