/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MarisIT.Api.Client.OpenAPIDateConverter;

namespace MarisIT.Api.Model
{
    /// <summary>
    /// TransunionConsumer118TRLTN01
    /// </summary>
    [DataContract]
    public partial class TransunionConsumer118TRLTN01 :  IEquatable<TransunionConsumer118TRLTN01>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransunionConsumer118TRLTN01" /> class.
        /// </summary>
        /// <param name="consumerNo">consumerNo.</param>
        /// <param name="applicationDate">applicationDate.</param>
        /// <param name="trlScore">trlScore.</param>
        /// <param name="maxAac1">maxAac1.</param>
        /// <param name="maxAac2">maxAac2.</param>
        /// <param name="maxAac3">maxAac3.</param>
        /// <param name="maxAac4">maxAac4.</param>
        /// <param name="maxAacVerb1">maxAacVerb1.</param>
        /// <param name="maxAacVerb2">maxAacVerb2.</param>
        /// <param name="maxAacVerb3">maxAacVerb3.</param>
        /// <param name="maxAacVerb4">maxAacVerb4.</param>
        public TransunionConsumer118TRLTN01(string consumerNo = default(string), string applicationDate = default(string), string trlScore = default(string), string maxAac1 = default(string), string maxAac2 = default(string), string maxAac3 = default(string), string maxAac4 = default(string), string maxAacVerb1 = default(string), string maxAacVerb2 = default(string), string maxAacVerb3 = default(string), string maxAacVerb4 = default(string))
        {
            this.ConsumerNo = consumerNo;
            this.ApplicationDate = applicationDate;
            this.TrlScore = trlScore;
            this.MaxAac1 = maxAac1;
            this.MaxAac2 = maxAac2;
            this.MaxAac3 = maxAac3;
            this.MaxAac4 = maxAac4;
            this.MaxAacVerb1 = maxAacVerb1;
            this.MaxAacVerb2 = maxAacVerb2;
            this.MaxAacVerb3 = maxAacVerb3;
            this.MaxAacVerb4 = maxAacVerb4;
            this.ConsumerNo = consumerNo;
            this.ApplicationDate = applicationDate;
            this.TrlScore = trlScore;
            this.MaxAac1 = maxAac1;
            this.MaxAac2 = maxAac2;
            this.MaxAac3 = maxAac3;
            this.MaxAac4 = maxAac4;
            this.MaxAacVerb1 = maxAacVerb1;
            this.MaxAacVerb2 = maxAacVerb2;
            this.MaxAacVerb3 = maxAacVerb3;
            this.MaxAacVerb4 = maxAacVerb4;
        }

        /// <summary>
        /// Gets or Sets ConsumerNo
        /// </summary>
        [DataMember(Name="consumer_no", EmitDefaultValue=true)]
        public string ConsumerNo { get; set; }

        /// <summary>
        /// Gets or Sets ApplicationDate
        /// </summary>
        [DataMember(Name="application_date", EmitDefaultValue=true)]
        public string ApplicationDate { get; set; }

        /// <summary>
        /// Gets or Sets TrlScore
        /// </summary>
        [DataMember(Name="trl_score", EmitDefaultValue=true)]
        public string TrlScore { get; set; }

        /// <summary>
        /// Gets or Sets MaxAac1
        /// </summary>
        [DataMember(Name="max_aac_1", EmitDefaultValue=true)]
        public string MaxAac1 { get; set; }

        /// <summary>
        /// Gets or Sets MaxAac2
        /// </summary>
        [DataMember(Name="max_aac_2", EmitDefaultValue=true)]
        public string MaxAac2 { get; set; }

        /// <summary>
        /// Gets or Sets MaxAac3
        /// </summary>
        [DataMember(Name="max_aac_3", EmitDefaultValue=true)]
        public string MaxAac3 { get; set; }

        /// <summary>
        /// Gets or Sets MaxAac4
        /// </summary>
        [DataMember(Name="max_aac_4", EmitDefaultValue=true)]
        public string MaxAac4 { get; set; }

        /// <summary>
        /// Gets or Sets MaxAacVerb1
        /// </summary>
        [DataMember(Name="max_aac_verb_1", EmitDefaultValue=true)]
        public string MaxAacVerb1 { get; set; }

        /// <summary>
        /// Gets or Sets MaxAacVerb2
        /// </summary>
        [DataMember(Name="max_aac_verb_2", EmitDefaultValue=true)]
        public string MaxAacVerb2 { get; set; }

        /// <summary>
        /// Gets or Sets MaxAacVerb3
        /// </summary>
        [DataMember(Name="max_aac_verb_3", EmitDefaultValue=true)]
        public string MaxAacVerb3 { get; set; }

        /// <summary>
        /// Gets or Sets MaxAacVerb4
        /// </summary>
        [DataMember(Name="max_aac_verb_4", EmitDefaultValue=true)]
        public string MaxAacVerb4 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransunionConsumer118TRLTN01 {\n");
            sb.Append("  ConsumerNo: ").Append(ConsumerNo).Append("\n");
            sb.Append("  ApplicationDate: ").Append(ApplicationDate).Append("\n");
            sb.Append("  TrlScore: ").Append(TrlScore).Append("\n");
            sb.Append("  MaxAac1: ").Append(MaxAac1).Append("\n");
            sb.Append("  MaxAac2: ").Append(MaxAac2).Append("\n");
            sb.Append("  MaxAac3: ").Append(MaxAac3).Append("\n");
            sb.Append("  MaxAac4: ").Append(MaxAac4).Append("\n");
            sb.Append("  MaxAacVerb1: ").Append(MaxAacVerb1).Append("\n");
            sb.Append("  MaxAacVerb2: ").Append(MaxAacVerb2).Append("\n");
            sb.Append("  MaxAacVerb3: ").Append(MaxAacVerb3).Append("\n");
            sb.Append("  MaxAacVerb4: ").Append(MaxAacVerb4).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransunionConsumer118TRLTN01);
        }

        /// <summary>
        /// Returns true if TransunionConsumer118TRLTN01 instances are equal
        /// </summary>
        /// <param name="input">Instance of TransunionConsumer118TRLTN01 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransunionConsumer118TRLTN01 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ConsumerNo == input.ConsumerNo ||
                    (this.ConsumerNo != null &&
                    this.ConsumerNo.Equals(input.ConsumerNo))
                ) && 
                (
                    this.ApplicationDate == input.ApplicationDate ||
                    (this.ApplicationDate != null &&
                    this.ApplicationDate.Equals(input.ApplicationDate))
                ) && 
                (
                    this.TrlScore == input.TrlScore ||
                    (this.TrlScore != null &&
                    this.TrlScore.Equals(input.TrlScore))
                ) && 
                (
                    this.MaxAac1 == input.MaxAac1 ||
                    (this.MaxAac1 != null &&
                    this.MaxAac1.Equals(input.MaxAac1))
                ) && 
                (
                    this.MaxAac2 == input.MaxAac2 ||
                    (this.MaxAac2 != null &&
                    this.MaxAac2.Equals(input.MaxAac2))
                ) && 
                (
                    this.MaxAac3 == input.MaxAac3 ||
                    (this.MaxAac3 != null &&
                    this.MaxAac3.Equals(input.MaxAac3))
                ) && 
                (
                    this.MaxAac4 == input.MaxAac4 ||
                    (this.MaxAac4 != null &&
                    this.MaxAac4.Equals(input.MaxAac4))
                ) && 
                (
                    this.MaxAacVerb1 == input.MaxAacVerb1 ||
                    (this.MaxAacVerb1 != null &&
                    this.MaxAacVerb1.Equals(input.MaxAacVerb1))
                ) && 
                (
                    this.MaxAacVerb2 == input.MaxAacVerb2 ||
                    (this.MaxAacVerb2 != null &&
                    this.MaxAacVerb2.Equals(input.MaxAacVerb2))
                ) && 
                (
                    this.MaxAacVerb3 == input.MaxAacVerb3 ||
                    (this.MaxAacVerb3 != null &&
                    this.MaxAacVerb3.Equals(input.MaxAacVerb3))
                ) && 
                (
                    this.MaxAacVerb4 == input.MaxAacVerb4 ||
                    (this.MaxAacVerb4 != null &&
                    this.MaxAacVerb4.Equals(input.MaxAacVerb4))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ConsumerNo != null)
                    hashCode = hashCode * 59 + this.ConsumerNo.GetHashCode();
                if (this.ApplicationDate != null)
                    hashCode = hashCode * 59 + this.ApplicationDate.GetHashCode();
                if (this.TrlScore != null)
                    hashCode = hashCode * 59 + this.TrlScore.GetHashCode();
                if (this.MaxAac1 != null)
                    hashCode = hashCode * 59 + this.MaxAac1.GetHashCode();
                if (this.MaxAac2 != null)
                    hashCode = hashCode * 59 + this.MaxAac2.GetHashCode();
                if (this.MaxAac3 != null)
                    hashCode = hashCode * 59 + this.MaxAac3.GetHashCode();
                if (this.MaxAac4 != null)
                    hashCode = hashCode * 59 + this.MaxAac4.GetHashCode();
                if (this.MaxAacVerb1 != null)
                    hashCode = hashCode * 59 + this.MaxAacVerb1.GetHashCode();
                if (this.MaxAacVerb2 != null)
                    hashCode = hashCode * 59 + this.MaxAacVerb2.GetHashCode();
                if (this.MaxAacVerb3 != null)
                    hashCode = hashCode * 59 + this.MaxAacVerb3.GetHashCode();
                if (this.MaxAacVerb4 != null)
                    hashCode = hashCode * 59 + this.MaxAacVerb4.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
