/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MarisIT.Api.Client.OpenAPIDateConverter;

namespace MarisIT.Api.Model
{
    /// <summary>
    /// WindeedCipcProxiesNaturalOrJuristicMember
    /// </summary>
    [DataContract]
    public partial class WindeedCipcProxiesNaturalOrJuristicMember :  IEquatable<WindeedCipcProxiesNaturalOrJuristicMember>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WindeedCipcProxiesNaturalOrJuristicMember" /> class.
        /// </summary>
        /// <param name="natural">natural.</param>
        /// <param name="jurisitc">jurisitc.</param>
        public WindeedCipcProxiesNaturalOrJuristicMember(WindeedCipcNaturalMember natural = default(WindeedCipcNaturalMember), WindeedCipcJuristicMember jurisitc = default(WindeedCipcJuristicMember))
        {
            this.Natural = natural;
            this.Jurisitc = jurisitc;
        }

        /// <summary>
        /// Gets or Sets Natural
        /// </summary>
        [DataMember(Name="natural", EmitDefaultValue=false)]
        public WindeedCipcNaturalMember Natural { get; set; }

        /// <summary>
        /// Gets or Sets Jurisitc
        /// </summary>
        [DataMember(Name="jurisitc", EmitDefaultValue=false)]
        public WindeedCipcJuristicMember Jurisitc { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WindeedCipcProxiesNaturalOrJuristicMember {\n");
            sb.Append("  Natural: ").Append(Natural).Append("\n");
            sb.Append("  Jurisitc: ").Append(Jurisitc).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WindeedCipcProxiesNaturalOrJuristicMember);
        }

        /// <summary>
        /// Returns true if WindeedCipcProxiesNaturalOrJuristicMember instances are equal
        /// </summary>
        /// <param name="input">Instance of WindeedCipcProxiesNaturalOrJuristicMember to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WindeedCipcProxiesNaturalOrJuristicMember input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Natural == input.Natural ||
                    (this.Natural != null &&
                    this.Natural.Equals(input.Natural))
                ) && 
                (
                    this.Jurisitc == input.Jurisitc ||
                    (this.Jurisitc != null &&
                    this.Jurisitc.Equals(input.Jurisitc))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Natural != null)
                    hashCode = hashCode * 59 + this.Natural.GetHashCode();
                if (this.Jurisitc != null)
                    hashCode = hashCode * 59 + this.Jurisitc.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
