/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MarisIT.Api.Client.OpenAPIDateConverter;

namespace MarisIT.Api.Model
{
    /// <summary>
    /// WindeedWprTransferHistory
    /// </summary>
    [DataContract]
    public partial class WindeedWprTransferHistory :  IEquatable<WindeedWprTransferHistory>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WindeedWprTransferHistory" /> class.
        /// </summary>
        /// <param name="buyers">buyers.</param>
        /// <param name="sellers">sellers.</param>
        /// <param name="registrationDate">registrationDate.</param>
        /// <param name="purchaseDate">purchaseDate.</param>
        /// <param name="purchasePrice">purchasePrice.</param>
        /// <param name="documentNumber">documentNumber.</param>
        /// <param name="institution">institution.</param>
        /// <param name="bondNumber">bondNumber.</param>
        /// <param name="bondAmount">bondAmount.</param>
        public WindeedWprTransferHistory(List<string> buyers = default(List<string>), List<string> sellers = default(List<string>), DateTime? registrationDate = default(DateTime?), DateTime? purchaseDate = default(DateTime?), string purchasePrice = default(string), string documentNumber = default(string), string institution = default(string), string bondNumber = default(string), string bondAmount = default(string))
        {
            this.Buyers = buyers;
            this.Sellers = sellers;
            this.RegistrationDate = registrationDate;
            this.PurchaseDate = purchaseDate;
            this.PurchasePrice = purchasePrice;
            this.DocumentNumber = documentNumber;
            this.Institution = institution;
            this.BondNumber = bondNumber;
            this.BondAmount = bondAmount;
            this.Buyers = buyers;
            this.Sellers = sellers;
            this.RegistrationDate = registrationDate;
            this.PurchaseDate = purchaseDate;
            this.PurchasePrice = purchasePrice;
            this.DocumentNumber = documentNumber;
            this.Institution = institution;
            this.BondNumber = bondNumber;
            this.BondAmount = bondAmount;
        }

        /// <summary>
        /// Gets or Sets Buyers
        /// </summary>
        [DataMember(Name="buyers", EmitDefaultValue=true)]
        public List<string> Buyers { get; set; }

        /// <summary>
        /// Gets or Sets Sellers
        /// </summary>
        [DataMember(Name="sellers", EmitDefaultValue=true)]
        public List<string> Sellers { get; set; }

        /// <summary>
        /// Gets or Sets RegistrationDate
        /// </summary>
        [DataMember(Name="registrationDate", EmitDefaultValue=true)]
        public DateTime? RegistrationDate { get; set; }

        /// <summary>
        /// Gets or Sets PurchaseDate
        /// </summary>
        [DataMember(Name="purchaseDate", EmitDefaultValue=true)]
        public DateTime? PurchaseDate { get; set; }

        /// <summary>
        /// Gets or Sets PurchasePrice
        /// </summary>
        [DataMember(Name="purchasePrice", EmitDefaultValue=true)]
        public string PurchasePrice { get; set; }

        /// <summary>
        /// Gets or Sets DocumentNumber
        /// </summary>
        [DataMember(Name="documentNumber", EmitDefaultValue=true)]
        public string DocumentNumber { get; set; }

        /// <summary>
        /// Gets or Sets Institution
        /// </summary>
        [DataMember(Name="institution", EmitDefaultValue=true)]
        public string Institution { get; set; }

        /// <summary>
        /// Gets or Sets BondNumber
        /// </summary>
        [DataMember(Name="bondNumber", EmitDefaultValue=true)]
        public string BondNumber { get; set; }

        /// <summary>
        /// Gets or Sets BondAmount
        /// </summary>
        [DataMember(Name="bondAmount", EmitDefaultValue=true)]
        public string BondAmount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WindeedWprTransferHistory {\n");
            sb.Append("  Buyers: ").Append(Buyers).Append("\n");
            sb.Append("  Sellers: ").Append(Sellers).Append("\n");
            sb.Append("  RegistrationDate: ").Append(RegistrationDate).Append("\n");
            sb.Append("  PurchaseDate: ").Append(PurchaseDate).Append("\n");
            sb.Append("  PurchasePrice: ").Append(PurchasePrice).Append("\n");
            sb.Append("  DocumentNumber: ").Append(DocumentNumber).Append("\n");
            sb.Append("  Institution: ").Append(Institution).Append("\n");
            sb.Append("  BondNumber: ").Append(BondNumber).Append("\n");
            sb.Append("  BondAmount: ").Append(BondAmount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WindeedWprTransferHistory);
        }

        /// <summary>
        /// Returns true if WindeedWprTransferHistory instances are equal
        /// </summary>
        /// <param name="input">Instance of WindeedWprTransferHistory to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WindeedWprTransferHistory input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Buyers == input.Buyers ||
                    this.Buyers != null &&
                    input.Buyers != null &&
                    this.Buyers.SequenceEqual(input.Buyers)
                ) && 
                (
                    this.Sellers == input.Sellers ||
                    this.Sellers != null &&
                    input.Sellers != null &&
                    this.Sellers.SequenceEqual(input.Sellers)
                ) && 
                (
                    this.RegistrationDate == input.RegistrationDate ||
                    (this.RegistrationDate != null &&
                    this.RegistrationDate.Equals(input.RegistrationDate))
                ) && 
                (
                    this.PurchaseDate == input.PurchaseDate ||
                    (this.PurchaseDate != null &&
                    this.PurchaseDate.Equals(input.PurchaseDate))
                ) && 
                (
                    this.PurchasePrice == input.PurchasePrice ||
                    (this.PurchasePrice != null &&
                    this.PurchasePrice.Equals(input.PurchasePrice))
                ) && 
                (
                    this.DocumentNumber == input.DocumentNumber ||
                    (this.DocumentNumber != null &&
                    this.DocumentNumber.Equals(input.DocumentNumber))
                ) && 
                (
                    this.Institution == input.Institution ||
                    (this.Institution != null &&
                    this.Institution.Equals(input.Institution))
                ) && 
                (
                    this.BondNumber == input.BondNumber ||
                    (this.BondNumber != null &&
                    this.BondNumber.Equals(input.BondNumber))
                ) && 
                (
                    this.BondAmount == input.BondAmount ||
                    (this.BondAmount != null &&
                    this.BondAmount.Equals(input.BondAmount))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Buyers != null)
                    hashCode = hashCode * 59 + this.Buyers.GetHashCode();
                if (this.Sellers != null)
                    hashCode = hashCode * 59 + this.Sellers.GetHashCode();
                if (this.RegistrationDate != null)
                    hashCode = hashCode * 59 + this.RegistrationDate.GetHashCode();
                if (this.PurchaseDate != null)
                    hashCode = hashCode * 59 + this.PurchaseDate.GetHashCode();
                if (this.PurchasePrice != null)
                    hashCode = hashCode * 59 + this.PurchasePrice.GetHashCode();
                if (this.DocumentNumber != null)
                    hashCode = hashCode * 59 + this.DocumentNumber.GetHashCode();
                if (this.Institution != null)
                    hashCode = hashCode * 59 + this.Institution.GetHashCode();
                if (this.BondNumber != null)
                    hashCode = hashCode * 59 + this.BondNumber.GetHashCode();
                if (this.BondAmount != null)
                    hashCode = hashCode * 59 + this.BondAmount.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
