/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MarisIT.Api.Client.OpenAPIDateConverter;

namespace MarisIT.Api.Model
{
    /// <summary>
    /// XdsConsumerLite
    /// </summary>
    [DataContract]
    public partial class XdsConsumerLite :  IEquatable<XdsConsumerLite>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="XdsConsumerLite" /> class.
        /// </summary>
        /// <param name="reportInformation">reportInformation.</param>
        /// <param name="consumerDetail">consumerDetail.</param>
        /// <param name="subscriberInputDetails">subscriberInputDetails.</param>
        /// <param name="consumerAddressHistory">consumerAddressHistory.</param>
        /// <param name="consumerTelephoneHistory">consumerTelephoneHistory.</param>
        public XdsConsumerLite(XdsReportInformation reportInformation = default(XdsReportInformation), XdsConsumerDetail consumerDetail = default(XdsConsumerDetail), XdsSubscriberInputDetails subscriberInputDetails = default(XdsSubscriberInputDetails), List<XdsConsumerAddressHistoryLite> consumerAddressHistory = default(List<XdsConsumerAddressHistoryLite>), List<XdsConsumerTelephoneHistoryLite> consumerTelephoneHistory = default(List<XdsConsumerTelephoneHistoryLite>))
        {
            this.ConsumerAddressHistory = consumerAddressHistory;
            this.ConsumerTelephoneHistory = consumerTelephoneHistory;
            this.ReportInformation = reportInformation;
            this.ConsumerDetail = consumerDetail;
            this.SubscriberInputDetails = subscriberInputDetails;
            this.ConsumerAddressHistory = consumerAddressHistory;
            this.ConsumerTelephoneHistory = consumerTelephoneHistory;
        }

        /// <summary>
        /// Gets or Sets ReportInformation
        /// </summary>
        [DataMember(Name="reportInformation", EmitDefaultValue=false)]
        public XdsReportInformation ReportInformation { get; set; }

        /// <summary>
        /// Gets or Sets ConsumerDetail
        /// </summary>
        [DataMember(Name="consumerDetail", EmitDefaultValue=false)]
        public XdsConsumerDetail ConsumerDetail { get; set; }

        /// <summary>
        /// Gets or Sets SubscriberInputDetails
        /// </summary>
        [DataMember(Name="subscriberInputDetails", EmitDefaultValue=false)]
        public XdsSubscriberInputDetails SubscriberInputDetails { get; set; }

        /// <summary>
        /// Gets or Sets ConsumerAddressHistory
        /// </summary>
        [DataMember(Name="consumerAddressHistory", EmitDefaultValue=true)]
        public List<XdsConsumerAddressHistoryLite> ConsumerAddressHistory { get; set; }

        /// <summary>
        /// Gets or Sets ConsumerTelephoneHistory
        /// </summary>
        [DataMember(Name="consumerTelephoneHistory", EmitDefaultValue=true)]
        public List<XdsConsumerTelephoneHistoryLite> ConsumerTelephoneHistory { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class XdsConsumerLite {\n");
            sb.Append("  ReportInformation: ").Append(ReportInformation).Append("\n");
            sb.Append("  ConsumerDetail: ").Append(ConsumerDetail).Append("\n");
            sb.Append("  SubscriberInputDetails: ").Append(SubscriberInputDetails).Append("\n");
            sb.Append("  ConsumerAddressHistory: ").Append(ConsumerAddressHistory).Append("\n");
            sb.Append("  ConsumerTelephoneHistory: ").Append(ConsumerTelephoneHistory).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as XdsConsumerLite);
        }

        /// <summary>
        /// Returns true if XdsConsumerLite instances are equal
        /// </summary>
        /// <param name="input">Instance of XdsConsumerLite to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(XdsConsumerLite input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ReportInformation == input.ReportInformation ||
                    (this.ReportInformation != null &&
                    this.ReportInformation.Equals(input.ReportInformation))
                ) && 
                (
                    this.ConsumerDetail == input.ConsumerDetail ||
                    (this.ConsumerDetail != null &&
                    this.ConsumerDetail.Equals(input.ConsumerDetail))
                ) && 
                (
                    this.SubscriberInputDetails == input.SubscriberInputDetails ||
                    (this.SubscriberInputDetails != null &&
                    this.SubscriberInputDetails.Equals(input.SubscriberInputDetails))
                ) && 
                (
                    this.ConsumerAddressHistory == input.ConsumerAddressHistory ||
                    this.ConsumerAddressHistory != null &&
                    input.ConsumerAddressHistory != null &&
                    this.ConsumerAddressHistory.SequenceEqual(input.ConsumerAddressHistory)
                ) && 
                (
                    this.ConsumerTelephoneHistory == input.ConsumerTelephoneHistory ||
                    this.ConsumerTelephoneHistory != null &&
                    input.ConsumerTelephoneHistory != null &&
                    this.ConsumerTelephoneHistory.SequenceEqual(input.ConsumerTelephoneHistory)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ReportInformation != null)
                    hashCode = hashCode * 59 + this.ReportInformation.GetHashCode();
                if (this.ConsumerDetail != null)
                    hashCode = hashCode * 59 + this.ConsumerDetail.GetHashCode();
                if (this.SubscriberInputDetails != null)
                    hashCode = hashCode * 59 + this.SubscriberInputDetails.GetHashCode();
                if (this.ConsumerAddressHistory != null)
                    hashCode = hashCode * 59 + this.ConsumerAddressHistory.GetHashCode();
                if (this.ConsumerTelephoneHistory != null)
                    hashCode = hashCode * 59 + this.ConsumerTelephoneHistory.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
