/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarisIT.Api.Api;
using MarisIT.Api.Model;
using MarisIT.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarisIT.Api.Test
{
    /// <summary>
    ///  Class for testing CompuscanCOMPCONTRACTS
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CompuscanCOMPCONTRACTSTests
    {
        // TODO uncomment below to declare an instance variable for CompuscanCOMPCONTRACTS
        //private CompuscanCOMPCONTRACTS instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CompuscanCOMPCONTRACTS
            //instance = new CompuscanCOMPCONTRACTS();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CompuscanCOMPCONTRACTS
        /// </summary>
        [Test]
        public void CompuscanCOMPCONTRACTSInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CompuscanCOMPCONTRACTS
            //Assert.IsInstanceOf(typeof(CompuscanCOMPCONTRACTS), instance);
        }


        /// <summary>
        /// Test the property 'Cmpnynm'
        /// </summary>
        [Test]
        public void CmpnynmTest()
        {
            // TODO unit test for the property 'Cmpnynm'
        }
        /// <summary>
        /// Test the property 'Cmpnyrgstrtn'
        /// </summary>
        [Test]
        public void CmpnyrgstrtnTest()
        {
            // TODO unit test for the property 'Cmpnyrgstrtn'
        }
        /// <summary>
        /// Test the property 'Cntrctamount'
        /// </summary>
        [Test]
        public void CntrctamountTest()
        {
            // TODO unit test for the property 'Cntrctamount'
        }
        /// <summary>
        /// Test the property 'Cntrctenddt'
        /// </summary>
        [Test]
        public void CntrctenddtTest()
        {
            // TODO unit test for the property 'Cntrctenddt'
        }
        /// <summary>
        /// Test the property 'Cntrctrfrnc'
        /// </summary>
        [Test]
        public void CntrctrfrncTest()
        {
            // TODO unit test for the property 'Cntrctrfrnc'
        }
        /// <summary>
        /// Test the property 'Cntrctstrtdt'
        /// </summary>
        [Test]
        public void CntrctstrtdtTest()
        {
            // TODO unit test for the property 'Cntrctstrtdt'
        }
        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [Test]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }
        /// <summary>
        /// Test the property 'Createdby'
        /// </summary>
        [Test]
        public void CreatedbyTest()
        {
            // TODO unit test for the property 'Createdby'
        }
        /// <summary>
        /// Test the property 'Createddttm'
        /// </summary>
        [Test]
        public void CreateddttmTest()
        {
            // TODO unit test for the property 'Createddttm'
        }
        /// <summary>
        /// Test the property 'Modifiedby'
        /// </summary>
        [Test]
        public void ModifiedbyTest()
        {
            // TODO unit test for the property 'Modifiedby'
        }
        /// <summary>
        /// Test the property 'Modifieddttm'
        /// </summary>
        [Test]
        public void ModifieddttmTest()
        {
            // TODO unit test for the property 'Modifieddttm'
        }
        /// <summary>
        /// Test the property 'Retentionperiod'
        /// </summary>
        [Test]
        public void RetentionperiodTest()
        {
            // TODO unit test for the property 'Retentionperiod'
        }

    }

}
