/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarisIT.Api.Api;
using MarisIT.Api.Model;
using MarisIT.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarisIT.Api.Test
{
    /// <summary>
    ///  Class for testing CompuscanCOMPPREVENQ
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CompuscanCOMPPREVENQTests
    {
        // TODO uncomment below to declare an instance variable for CompuscanCOMPPREVENQ
        //private CompuscanCOMPPREVENQ instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CompuscanCOMPPREVENQ
            //instance = new CompuscanCOMPPREVENQ();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CompuscanCOMPPREVENQ
        /// </summary>
        [Test]
        public void CompuscanCOMPPREVENQInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CompuscanCOMPPREVENQ
            //Assert.IsInstanceOf(typeof(CompuscanCOMPPREVENQ), instance);
        }


        /// <summary>
        /// Test the property 'Branchname'
        /// </summary>
        [Test]
        public void BranchnameTest()
        {
            // TODO unit test for the property 'Branchname'
        }
        /// <summary>
        /// Test the property 'Contactperson'
        /// </summary>
        [Test]
        public void ContactpersonTest()
        {
            // TODO unit test for the property 'Contactperson'
        }
        /// <summary>
        /// Test the property 'Enqdate'
        /// </summary>
        [Test]
        public void EnqdateTest()
        {
            // TODO unit test for the property 'Enqdate'
        }
        /// <summary>
        /// Test the property 'Telephonenumber'
        /// </summary>
        [Test]
        public void TelephonenumberTest()
        {
            // TODO unit test for the property 'Telephonenumber'
        }

    }

}
