/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarisIT.Api.Api;
using MarisIT.Api.Model;
using MarisIT.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarisIT.Api.Test
{
    /// <summary>
    ///  Class for testing TransunionCommercialNames
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransunionCommercialNamesTests
    {
        // TODO uncomment below to declare an instance variable for TransunionCommercialNames
        //private TransunionCommercialNames instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransunionCommercialNames
            //instance = new TransunionCommercialNames();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransunionCommercialNames
        /// </summary>
        [Test]
        public void TransunionCommercialNamesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TransunionCommercialNames
            //Assert.IsInstanceOf(typeof(TransunionCommercialNames), instance);
        }


        /// <summary>
        /// Test the property 'MajorProduct'
        /// </summary>
        [Test]
        public void MajorProductTest()
        {
            // TODO unit test for the property 'MajorProduct'
        }
        /// <summary>
        /// Test the property 'BusinessName'
        /// </summary>
        [Test]
        public void BusinessNameTest()
        {
            // TODO unit test for the property 'BusinessName'
        }
        /// <summary>
        /// Test the property 'AkaName'
        /// </summary>
        [Test]
        public void AkaNameTest()
        {
            // TODO unit test for the property 'AkaName'
        }
        /// <summary>
        /// Test the property 'DivisionalNames'
        /// </summary>
        [Test]
        public void DivisionalNamesTest()
        {
            // TODO unit test for the property 'DivisionalNames'
        }
        /// <summary>
        /// Test the property 'PreviousNames'
        /// </summary>
        [Test]
        public void PreviousNamesTest()
        {
            // TODO unit test for the property 'PreviousNames'
        }
        /// <summary>
        /// Test the property 'PreviousNameDates'
        /// </summary>
        [Test]
        public void PreviousNameDatesTest()
        {
            // TODO unit test for the property 'PreviousNameDates'
        }
        /// <summary>
        /// Test the property 'TradeStyles'
        /// </summary>
        [Test]
        public void TradeStylesTest()
        {
            // TODO unit test for the property 'TradeStyles'
        }

    }

}
