/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarisIT.Api.Api;
using MarisIT.Api.Model;
using MarisIT.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarisIT.Api.Test
{
    /// <summary>
    ///  Class for testing TransunionConsumer118EnquiryNE51
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransunionConsumer118EnquiryNE51Tests
    {
        // TODO uncomment below to declare an instance variable for TransunionConsumer118EnquiryNE51
        //private TransunionConsumer118EnquiryNE51 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransunionConsumer118EnquiryNE51
            //instance = new TransunionConsumer118EnquiryNE51();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransunionConsumer118EnquiryNE51
        /// </summary>
        [Test]
        public void TransunionConsumer118EnquiryNE51InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TransunionConsumer118EnquiryNE51
            //Assert.IsInstanceOf(typeof(TransunionConsumer118EnquiryNE51), instance);
        }


        /// <summary>
        /// Test the property 'ConsumerNo'
        /// </summary>
        [Test]
        public void ConsumerNoTest()
        {
            // TODO unit test for the property 'ConsumerNo'
        }
        /// <summary>
        /// Test the property 'DateOfEnquiry'
        /// </summary>
        [Test]
        public void DateOfEnquiryTest()
        {
            // TODO unit test for the property 'DateOfEnquiry'
        }
        /// <summary>
        /// Test the property 'Subscriber'
        /// </summary>
        [Test]
        public void SubscriberTest()
        {
            // TODO unit test for the property 'Subscriber'
        }
        /// <summary>
        /// Test the property 'Contact'
        /// </summary>
        [Test]
        public void ContactTest()
        {
            // TODO unit test for the property 'Contact'
        }
        /// <summary>
        /// Test the property 'EnquiryTypeCode'
        /// </summary>
        [Test]
        public void EnquiryTypeCodeTest()
        {
            // TODO unit test for the property 'EnquiryTypeCode'
        }
        /// <summary>
        /// Test the property 'EnquiryTypeDescription'
        /// </summary>
        [Test]
        public void EnquiryTypeDescriptionTest()
        {
            // TODO unit test for the property 'EnquiryTypeDescription'
        }
        /// <summary>
        /// Test the property 'OwnAccount'
        /// </summary>
        [Test]
        public void OwnAccountTest()
        {
            // TODO unit test for the property 'OwnAccount'
        }
        /// <summary>
        /// Test the property 'InformationMessage'
        /// </summary>
        [Test]
        public void InformationMessageTest()
        {
            // TODO unit test for the property 'InformationMessage'
        }

    }

}
