/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarisIT.Api.Api;
using MarisIT.Api.Model;
using MarisIT.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarisIT.Api.Test
{
    /// <summary>
    ///  Class for testing TransunionCommercialPrincipalLinkPL
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransunionCommercialPrincipalLinkPLTests
    {
        // TODO uncomment below to declare an instance variable for TransunionCommercialPrincipalLinkPL
        //private TransunionCommercialPrincipalLinkPL instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransunionCommercialPrincipalLinkPL
            //instance = new TransunionCommercialPrincipalLinkPL();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransunionCommercialPrincipalLinkPL
        /// </summary>
        [Test]
        public void TransunionCommercialPrincipalLinkPLInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TransunionCommercialPrincipalLinkPL
            //Assert.IsInstanceOf(typeof(TransunionCommercialPrincipalLinkPL), instance);
        }


        /// <summary>
        /// Test the property 'MajorProduct'
        /// </summary>
        [Test]
        public void MajorProductTest()
        {
            // TODO unit test for the property 'MajorProduct'
        }
        /// <summary>
        /// Test the property 'ItNumber'
        /// </summary>
        [Test]
        public void ItNumberTest()
        {
            // TODO unit test for the property 'ItNumber'
        }
        /// <summary>
        /// Test the property 'ConsumerNumber'
        /// </summary>
        [Test]
        public void ConsumerNumberTest()
        {
            // TODO unit test for the property 'ConsumerNumber'
        }
        /// <summary>
        /// Test the property 'Surname'
        /// </summary>
        [Test]
        public void SurnameTest()
        {
            // TODO unit test for the property 'Surname'
        }
        /// <summary>
        /// Test the property 'Forename1'
        /// </summary>
        [Test]
        public void Forename1Test()
        {
            // TODO unit test for the property 'Forename1'
        }
        /// <summary>
        /// Test the property 'Forename2'
        /// </summary>
        [Test]
        public void Forename2Test()
        {
            // TODO unit test for the property 'Forename2'
        }
        /// <summary>
        /// Test the property 'Forename3'
        /// </summary>
        [Test]
        public void Forename3Test()
        {
            // TODO unit test for the property 'Forename3'
        }
        /// <summary>
        /// Test the property 'IdNumber'
        /// </summary>
        [Test]
        public void IdNumberTest()
        {
            // TODO unit test for the property 'IdNumber'
        }
        /// <summary>
        /// Test the property 'DateOfBirth'
        /// </summary>
        [Test]
        public void DateOfBirthTest()
        {
            // TODO unit test for the property 'DateOfBirth'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'Comment'
        /// </summary>
        [Test]
        public void CommentTest()
        {
            // TODO unit test for the property 'Comment'
        }
        /// <summary>
        /// Test the property 'ConsumerSurname1'
        /// </summary>
        [Test]
        public void ConsumerSurname1Test()
        {
            // TODO unit test for the property 'ConsumerSurname1'
        }
        /// <summary>
        /// Test the property 'ConsumerSurname2'
        /// </summary>
        [Test]
        public void ConsumerSurname2Test()
        {
            // TODO unit test for the property 'ConsumerSurname2'
        }
        /// <summary>
        /// Test the property 'ConsumerForename1'
        /// </summary>
        [Test]
        public void ConsumerForename1Test()
        {
            // TODO unit test for the property 'ConsumerForename1'
        }
        /// <summary>
        /// Test the property 'ConsumerForename2'
        /// </summary>
        [Test]
        public void ConsumerForename2Test()
        {
            // TODO unit test for the property 'ConsumerForename2'
        }
        /// <summary>
        /// Test the property 'ConsumerForename3'
        /// </summary>
        [Test]
        public void ConsumerForename3Test()
        {
            // TODO unit test for the property 'ConsumerForename3'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'HomeTelephoneList'
        /// </summary>
        [Test]
        public void HomeTelephoneListTest()
        {
            // TODO unit test for the property 'HomeTelephoneList'
        }
        /// <summary>
        /// Test the property 'WorkTelephoneList'
        /// </summary>
        [Test]
        public void WorkTelephoneListTest()
        {
            // TODO unit test for the property 'WorkTelephoneList'
        }

    }

}
