/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarisIT.Api.Api;
using MarisIT.Api.Model;
using MarisIT.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarisIT.Api.Test
{
    /// <summary>
    ///  Class for testing TransunionConsumer118ConsumerMiscellaneousMS
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransunionConsumer118ConsumerMiscellaneousMSTests
    {
        // TODO uncomment below to declare an instance variable for TransunionConsumer118ConsumerMiscellaneousMS
        //private TransunionConsumer118ConsumerMiscellaneousMS instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransunionConsumer118ConsumerMiscellaneousMS
            //instance = new TransunionConsumer118ConsumerMiscellaneousMS();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransunionConsumer118ConsumerMiscellaneousMS
        /// </summary>
        [Test]
        public void TransunionConsumer118ConsumerMiscellaneousMSInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TransunionConsumer118ConsumerMiscellaneousMS
            //Assert.IsInstanceOf(typeof(TransunionConsumer118ConsumerMiscellaneousMS), instance);
        }


        /// <summary>
        /// Test the property 'RecordSequence'
        /// </summary>
        [Test]
        public void RecordSequenceTest()
        {
            // TODO unit test for the property 'RecordSequence'
        }
        /// <summary>
        /// Test the property 'PartNumber'
        /// </summary>
        [Test]
        public void PartNumberTest()
        {
            // TODO unit test for the property 'PartNumber'
        }
        /// <summary>
        /// Test the property 'PartSequence'
        /// </summary>
        [Test]
        public void PartSequenceTest()
        {
            // TODO unit test for the property 'PartSequence'
        }
        /// <summary>
        /// Test the property 'ConsumerNo'
        /// </summary>
        [Test]
        public void ConsumerNoTest()
        {
            // TODO unit test for the property 'ConsumerNo'
        }
        /// <summary>
        /// Test the property 'InfoDate'
        /// </summary>
        [Test]
        public void InfoDateTest()
        {
            // TODO unit test for the property 'InfoDate'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Remarks'
        /// </summary>
        [Test]
        public void RemarksTest()
        {
            // TODO unit test for the property 'Remarks'
        }
        /// <summary>
        /// Test the property 'Remarks1'
        /// </summary>
        [Test]
        public void Remarks1Test()
        {
            // TODO unit test for the property 'Remarks1'
        }

    }

}
