/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarisIT.Api.Api;
using MarisIT.Api.Model;
using MarisIT.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarisIT.Api.Test
{
    /// <summary>
    ///  Class for testing TransunionCommercialPrincipalDeedsSummaryP8
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransunionCommercialPrincipalDeedsSummaryP8Tests
    {
        // TODO uncomment below to declare an instance variable for TransunionCommercialPrincipalDeedsSummaryP8
        //private TransunionCommercialPrincipalDeedsSummaryP8 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransunionCommercialPrincipalDeedsSummaryP8
            //instance = new TransunionCommercialPrincipalDeedsSummaryP8();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransunionCommercialPrincipalDeedsSummaryP8
        /// </summary>
        [Test]
        public void TransunionCommercialPrincipalDeedsSummaryP8InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TransunionCommercialPrincipalDeedsSummaryP8
            //Assert.IsInstanceOf(typeof(TransunionCommercialPrincipalDeedsSummaryP8), instance);
        }


        /// <summary>
        /// Test the property 'MajorProduct'
        /// </summary>
        [Test]
        public void MajorProductTest()
        {
            // TODO unit test for the property 'MajorProduct'
        }
        /// <summary>
        /// Test the property 'BusinessName'
        /// </summary>
        [Test]
        public void BusinessNameTest()
        {
            // TODO unit test for the property 'BusinessName'
        }
        /// <summary>
        /// Test the property 'RegistrationNumber'
        /// </summary>
        [Test]
        public void RegistrationNumberTest()
        {
            // TODO unit test for the property 'RegistrationNumber'
        }
        /// <summary>
        /// Test the property 'PrincipalName'
        /// </summary>
        [Test]
        public void PrincipalNameTest()
        {
            // TODO unit test for the property 'PrincipalName'
        }
        /// <summary>
        /// Test the property 'DateOfBirthOrIDNumber'
        /// </summary>
        [Test]
        public void DateOfBirthOrIDNumberTest()
        {
            // TODO unit test for the property 'DateOfBirthOrIDNumber'
        }
        /// <summary>
        /// Test the property 'NumberOfProperties'
        /// </summary>
        [Test]
        public void NumberOfPropertiesTest()
        {
            // TODO unit test for the property 'NumberOfProperties'
        }
        /// <summary>
        /// Test the property 'PurchasePrice'
        /// </summary>
        [Test]
        public void PurchasePriceTest()
        {
            // TODO unit test for the property 'PurchasePrice'
        }
        /// <summary>
        /// Test the property 'BondAmount'
        /// </summary>
        [Test]
        public void BondAmountTest()
        {
            // TODO unit test for the property 'BondAmount'
        }
        /// <summary>
        /// Test the property 'BondFreeAmount'
        /// </summary>
        [Test]
        public void BondFreeAmountTest()
        {
            // TODO unit test for the property 'BondFreeAmount'
        }
        /// <summary>
        /// Test the property 'DeedsOffice'
        /// </summary>
        [Test]
        public void DeedsOfficeTest()
        {
            // TODO unit test for the property 'DeedsOffice'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'BondCount'
        /// </summary>
        [Test]
        public void BondCountTest()
        {
            // TODO unit test for the property 'BondCount'
        }

    }

}
