/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarisIT.Api.Api;
using MarisIT.Api.Model;
using MarisIT.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarisIT.Api.Test
{
    /// <summary>
    ///  Class for testing TransunionConsumer118IndivualOwnOtherInactivePoliciesP1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransunionConsumer118IndivualOwnOtherInactivePoliciesP1Tests
    {
        // TODO uncomment below to declare an instance variable for TransunionConsumer118IndivualOwnOtherInactivePoliciesP1
        //private TransunionConsumer118IndivualOwnOtherInactivePoliciesP1 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransunionConsumer118IndivualOwnOtherInactivePoliciesP1
            //instance = new TransunionConsumer118IndivualOwnOtherInactivePoliciesP1();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransunionConsumer118IndivualOwnOtherInactivePoliciesP1
        /// </summary>
        [Test]
        public void TransunionConsumer118IndivualOwnOtherInactivePoliciesP1InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TransunionConsumer118IndivualOwnOtherInactivePoliciesP1
            //Assert.IsInstanceOf(typeof(TransunionConsumer118IndivualOwnOtherInactivePoliciesP1), instance);
        }


        /// <summary>
        /// Test the property 'RequestIndicator'
        /// </summary>
        [Test]
        public void RequestIndicatorTest()
        {
            // TODO unit test for the property 'RequestIndicator'
        }
        /// <summary>
        /// Test the property 'OwnOtherActivePolicyIndicator'
        /// </summary>
        [Test]
        public void OwnOtherActivePolicyIndicatorTest()
        {
            // TODO unit test for the property 'OwnOtherActivePolicyIndicator'
        }
        /// <summary>
        /// Test the property 'InsurerName'
        /// </summary>
        [Test]
        public void InsurerNameTest()
        {
            // TODO unit test for the property 'InsurerName'
        }
        /// <summary>
        /// Test the property 'PolicyNumber'
        /// </summary>
        [Test]
        public void PolicyNumberTest()
        {
            // TODO unit test for the property 'PolicyNumber'
        }
        /// <summary>
        /// Test the property 'RiskType'
        /// </summary>
        [Test]
        public void RiskTypeTest()
        {
            // TODO unit test for the property 'RiskType'
        }
        /// <summary>
        /// Test the property 'PolicyStatus'
        /// </summary>
        [Test]
        public void PolicyStatusTest()
        {
            // TODO unit test for the property 'PolicyStatus'
        }
        /// <summary>
        /// Test the property 'PolicyInceptionDate'
        /// </summary>
        [Test]
        public void PolicyInceptionDateTest()
        {
            // TODO unit test for the property 'PolicyInceptionDate'
        }
        /// <summary>
        /// Test the property 'PolicyCancellationDate'
        /// </summary>
        [Test]
        public void PolicyCancellationDateTest()
        {
            // TODO unit test for the property 'PolicyCancellationDate'
        }

    }

}
