/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarisIT.Api.Api;
using MarisIT.Api.Model;
using MarisIT.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarisIT.Api.Test
{
    /// <summary>
    ///  Class for testing TransunionConsumer118BreakdownDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransunionConsumer118BreakdownDTOTests
    {
        // TODO uncomment below to declare an instance variable for TransunionConsumer118BreakdownDTO
        //private TransunionConsumer118BreakdownDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransunionConsumer118BreakdownDTO
            //instance = new TransunionConsumer118BreakdownDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransunionConsumer118BreakdownDTO
        /// </summary>
        [Test]
        public void TransunionConsumer118BreakdownDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TransunionConsumer118BreakdownDTO
            //Assert.IsInstanceOf(typeof(TransunionConsumer118BreakdownDTO), instance);
        }


        /// <summary>
        /// Test the property 'Income'
        /// </summary>
        [Test]
        public void IncomeTest()
        {
            // TODO unit test for the property 'Income'
        }
        /// <summary>
        /// Test the property 'Deductions'
        /// </summary>
        [Test]
        public void DeductionsTest()
        {
            // TODO unit test for the property 'Deductions'
        }

    }

}
