/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarisIT.Api.Api;
using MarisIT.Api.Model;
using MarisIT.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarisIT.Api.Test
{
    /// <summary>
    ///  Class for testing TransunionConsumer118PhoneNumber
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransunionConsumer118PhoneNumberTests
    {
        // TODO uncomment below to declare an instance variable for TransunionConsumer118PhoneNumber
        //private TransunionConsumer118PhoneNumber instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransunionConsumer118PhoneNumber
            //instance = new TransunionConsumer118PhoneNumber();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransunionConsumer118PhoneNumber
        /// </summary>
        [Test]
        public void TransunionConsumer118PhoneNumberInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TransunionConsumer118PhoneNumber
            //Assert.IsInstanceOf(typeof(TransunionConsumer118PhoneNumber), instance);
        }


        /// <summary>
        /// Test the property 'AreaCode'
        /// </summary>
        [Test]
        public void AreaCodeTest()
        {
            // TODO unit test for the property 'AreaCode'
        }
        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Test]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Years'
        /// </summary>
        [Test]
        public void YearsTest()
        {
            // TODO unit test for the property 'Years'
        }

    }

}
