/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarisIT.Api.Api;
using MarisIT.Api.Model;
using MarisIT.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarisIT.Api.Test
{
    /// <summary>
    ///  Class for testing WindeedAgriculturalSearchRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WindeedAgriculturalSearchRequestTests
    {
        // TODO uncomment below to declare an instance variable for WindeedAgriculturalSearchRequest
        //private WindeedAgriculturalSearchRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WindeedAgriculturalSearchRequest
            //instance = new WindeedAgriculturalSearchRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WindeedAgriculturalSearchRequest
        /// </summary>
        [Test]
        public void WindeedAgriculturalSearchRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" WindeedAgriculturalSearchRequest
            //Assert.IsInstanceOf(typeof(WindeedAgriculturalSearchRequest), instance);
        }


        /// <summary>
        /// Test the property 'HoldingName'
        /// </summary>
        [Test]
        public void HoldingNameTest()
        {
            // TODO unit test for the property 'HoldingName'
        }
        /// <summary>
        /// Test the property 'HoldingNumber'
        /// </summary>
        [Test]
        public void HoldingNumberTest()
        {
            // TODO unit test for the property 'HoldingNumber'
        }
        /// <summary>
        /// Test the property 'PortionNumber'
        /// </summary>
        [Test]
        public void PortionNumberTest()
        {
            // TODO unit test for the property 'PortionNumber'
        }
        /// <summary>
        /// Test the property 'DeedsOffice'
        /// </summary>
        [Test]
        public void DeedsOfficeTest()
        {
            // TODO unit test for the property 'DeedsOffice'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Test]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }

    }

}
