/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarisIT.Api.Api;
using MarisIT.Api.Model;
using MarisIT.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarisIT.Api.Test
{
    /// <summary>
    ///  Class for testing WindeedCipcJuristicDirectorReportResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WindeedCipcJuristicDirectorReportResponseTests
    {
        // TODO uncomment below to declare an instance variable for WindeedCipcJuristicDirectorReportResponse
        //private WindeedCipcJuristicDirectorReportResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WindeedCipcJuristicDirectorReportResponse
            //instance = new WindeedCipcJuristicDirectorReportResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WindeedCipcJuristicDirectorReportResponse
        /// </summary>
        [Test]
        public void WindeedCipcJuristicDirectorReportResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" WindeedCipcJuristicDirectorReportResponse
            //Assert.IsInstanceOf(typeof(WindeedCipcJuristicDirectorReportResponse), instance);
        }


        /// <summary>
        /// Test the property 'DbKey'
        /// </summary>
        [Test]
        public void DbKeyTest()
        {
            // TODO unit test for the property 'DbKey'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'SouthAfricanResident'
        /// </summary>
        [Test]
        public void SouthAfricanResidentTest()
        {
            // TODO unit test for the property 'SouthAfricanResident'
        }
        /// <summary>
        /// Test the property 'AssociatedCompanies'
        /// </summary>
        [Test]
        public void AssociatedCompaniesTest()
        {
            // TODO unit test for the property 'AssociatedCompanies'
        }
        /// <summary>
        /// Test the property 'Nationality'
        /// </summary>
        [Test]
        public void NationalityTest()
        {
            // TODO unit test for the property 'Nationality'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'RegistrationNumber'
        /// </summary>
        [Test]
        public void RegistrationNumberTest()
        {
            // TODO unit test for the property 'RegistrationNumber'
        }

    }

}
