/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarisIT.Api.Api;
using MarisIT.Api.Model;
using MarisIT.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarisIT.Api.Test
{
    /// <summary>
    ///  Class for testing WindeedOfficeSummaryTitleDeed
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WindeedOfficeSummaryTitleDeedTests
    {
        // TODO uncomment below to declare an instance variable for WindeedOfficeSummaryTitleDeed
        //private WindeedOfficeSummaryTitleDeed instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WindeedOfficeSummaryTitleDeed
            //instance = new WindeedOfficeSummaryTitleDeed();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WindeedOfficeSummaryTitleDeed
        /// </summary>
        [Test]
        public void WindeedOfficeSummaryTitleDeedInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" WindeedOfficeSummaryTitleDeed
            //Assert.IsInstanceOf(typeof(WindeedOfficeSummaryTitleDeed), instance);
        }


        /// <summary>
        /// Test the property 'DocumentNumber'
        /// </summary>
        [Test]
        public void DocumentNumberTest()
        {
            // TODO unit test for the property 'DocumentNumber'
        }
        /// <summary>
        /// Test the property 'MicrofilmNumber'
        /// </summary>
        [Test]
        public void MicrofilmNumberTest()
        {
            // TODO unit test for the property 'MicrofilmNumber'
        }
        /// <summary>
        /// Test the property 'TypeCode'
        /// </summary>
        [Test]
        public void TypeCodeTest()
        {
            // TODO unit test for the property 'TypeCode'
        }
        /// <summary>
        /// Test the property 'TypeDescription'
        /// </summary>
        [Test]
        public void TypeDescriptionTest()
        {
            // TODO unit test for the property 'TypeDescription'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'PurchaseType'
        /// </summary>
        [Test]
        public void PurchaseTypeTest()
        {
            // TODO unit test for the property 'PurchaseType'
        }
        /// <summary>
        /// Test the property 'MultiOwner'
        /// </summary>
        [Test]
        public void MultiOwnerTest()
        {
            // TODO unit test for the property 'MultiOwner'
        }
        /// <summary>
        /// Test the property 'MultiProperty'
        /// </summary>
        [Test]
        public void MultiPropertyTest()
        {
            // TODO unit test for the property 'MultiProperty'
        }
        /// <summary>
        /// Test the property 'PurchaseDate'
        /// </summary>
        [Test]
        public void PurchaseDateTest()
        {
            // TODO unit test for the property 'PurchaseDate'
        }
        /// <summary>
        /// Test the property 'RegistrationDate'
        /// </summary>
        [Test]
        public void RegistrationDateTest()
        {
            // TODO unit test for the property 'RegistrationDate'
        }
        /// <summary>
        /// Test the property 'Share'
        /// </summary>
        [Test]
        public void ShareTest()
        {
            // TODO unit test for the property 'Share'
        }

    }

}
