/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarisIT.Api.Api;
using MarisIT.Api.Model;
using MarisIT.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarisIT.Api.Test
{
    /// <summary>
    ///  Class for testing WindeedLightstoneProxiesLightstoneValuationShortResponseFlatten
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WindeedLightstoneProxiesLightstoneValuationShortResponseFlattenTests
    {
        // TODO uncomment below to declare an instance variable for WindeedLightstoneProxiesLightstoneValuationShortResponseFlatten
        //private WindeedLightstoneProxiesLightstoneValuationShortResponseFlatten instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WindeedLightstoneProxiesLightstoneValuationShortResponseFlatten
            //instance = new WindeedLightstoneProxiesLightstoneValuationShortResponseFlatten();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WindeedLightstoneProxiesLightstoneValuationShortResponseFlatten
        /// </summary>
        [Test]
        public void WindeedLightstoneProxiesLightstoneValuationShortResponseFlattenInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" WindeedLightstoneProxiesLightstoneValuationShortResponseFlatten
            //Assert.IsInstanceOf(typeof(WindeedLightstoneProxiesLightstoneValuationShortResponseFlatten), instance);
        }


        /// <summary>
        /// Test the property 'SearchId'
        /// </summary>
        [Test]
        public void SearchIdTest()
        {
            // TODO unit test for the property 'SearchId'
        }
        /// <summary>
        /// Test the property 'Property'
        /// </summary>
        [Test]
        public void PropertyTest()
        {
            // TODO unit test for the property 'Property'
        }
        /// <summary>
        /// Test the property 'Owners'
        /// </summary>
        [Test]
        public void OwnersTest()
        {
            // TODO unit test for the property 'Owners'
        }
        /// <summary>
        /// Test the property 'SuburbSalesAmountGraph'
        /// </summary>
        [Test]
        public void SuburbSalesAmountGraphTest()
        {
            // TODO unit test for the property 'SuburbSalesAmountGraph'
        }
        /// <summary>
        /// Test the property 'SuburbSalesQuantityGraph'
        /// </summary>
        [Test]
        public void SuburbSalesQuantityGraphTest()
        {
            // TODO unit test for the property 'SuburbSalesQuantityGraph'
        }
        /// <summary>
        /// Test the property 'Map'
        /// </summary>
        [Test]
        public void MapTest()
        {
            // TODO unit test for the property 'Map'
        }
        /// <summary>
        /// Test the property 'AerialPhotograph'
        /// </summary>
        [Test]
        public void AerialPhotographTest()
        {
            // TODO unit test for the property 'AerialPhotograph'
        }
        /// <summary>
        /// Test the property 'GoogleMap'
        /// </summary>
        [Test]
        public void GoogleMapTest()
        {
            // TODO unit test for the property 'GoogleMap'
        }
        /// <summary>
        /// Test the property 'ComparativeSales'
        /// </summary>
        [Test]
        public void ComparativeSalesTest()
        {
            // TODO unit test for the property 'ComparativeSales'
        }
        /// <summary>
        /// Test the property 'Bonds'
        /// </summary>
        [Test]
        public void BondsTest()
        {
            // TODO unit test for the property 'Bonds'
        }
        /// <summary>
        /// Test the property 'MunicipalValuation'
        /// </summary>
        [Test]
        public void MunicipalValuationTest()
        {
            // TODO unit test for the property 'MunicipalValuation'
        }
        /// <summary>
        /// Test the property 'Amenities'
        /// </summary>
        [Test]
        public void AmenitiesTest()
        {
            // TODO unit test for the property 'Amenities'
        }
        /// <summary>
        /// Test the property 'Transfers'
        /// </summary>
        [Test]
        public void TransfersTest()
        {
            // TODO unit test for the property 'Transfers'
        }
        /// <summary>
        /// Test the property 'LastSale'
        /// </summary>
        [Test]
        public void LastSaleTest()
        {
            // TODO unit test for the property 'LastSale'
        }

    }

}
