/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarisIT.Api.Api;
using MarisIT.Api.Model;
using MarisIT.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarisIT.Api.Test
{
    /// <summary>
    ///  Class for testing WindeedCipcRegistrationNumber
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WindeedCipcRegistrationNumberTests
    {
        // TODO uncomment below to declare an instance variable for WindeedCipcRegistrationNumber
        //private WindeedCipcRegistrationNumber instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WindeedCipcRegistrationNumber
            //instance = new WindeedCipcRegistrationNumber();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WindeedCipcRegistrationNumber
        /// </summary>
        [Test]
        public void WindeedCipcRegistrationNumberInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" WindeedCipcRegistrationNumber
            //Assert.IsInstanceOf(typeof(WindeedCipcRegistrationNumber), instance);
        }


        /// <summary>
        /// Test the property 'Prefix'
        /// </summary>
        [Test]
        public void PrefixTest()
        {
            // TODO unit test for the property 'Prefix'
        }
        /// <summary>
        /// Test the property 'UniqueRegNumber'
        /// </summary>
        [Test]
        public void UniqueRegNumberTest()
        {
            // TODO unit test for the property 'UniqueRegNumber'
        }
        /// <summary>
        /// Test the property 'FullRegNumber'
        /// </summary>
        [Test]
        public void FullRegNumberTest()
        {
            // TODO unit test for the property 'FullRegNumber'
        }
        /// <summary>
        /// Test the property 'RegNumber'
        /// </summary>
        [Test]
        public void RegNumberTest()
        {
            // TODO unit test for the property 'RegNumber'
        }

    }

}
