/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarisIT.Api.Api;
using MarisIT.Api.Model;
using MarisIT.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarisIT.Api.Test
{
    /// <summary>
    ///  Class for testing XdsConsumerAccountStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class XdsConsumerAccountStatusTests
    {
        // TODO uncomment below to declare an instance variable for XdsConsumerAccountStatus
        //private XdsConsumerAccountStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of XdsConsumerAccountStatus
            //instance = new XdsConsumerAccountStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of XdsConsumerAccountStatus
        /// </summary>
        [Test]
        public void XdsConsumerAccountStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" XdsConsumerAccountStatus
            //Assert.IsInstanceOf(typeof(XdsConsumerAccountStatus), instance);
        }


        /// <summary>
        /// Test the property 'AccountNo'
        /// </summary>
        [Test]
        public void AccountNoTest()
        {
            // TODO unit test for the property 'AccountNo'
        }
        /// <summary>
        /// Test the property 'AccountOpenedDate'
        /// </summary>
        [Test]
        public void AccountOpenedDateTest()
        {
            // TODO unit test for the property 'AccountOpenedDate'
        }
        /// <summary>
        /// Test the property 'AccountType'
        /// </summary>
        [Test]
        public void AccountTypeTest()
        {
            // TODO unit test for the property 'AccountType'
        }
        /// <summary>
        /// Test the property 'ArrearsAmt'
        /// </summary>
        [Test]
        public void ArrearsAmtTest()
        {
            // TODO unit test for the property 'ArrearsAmt'
        }
        /// <summary>
        /// Test the property 'ArrearsTypeInd'
        /// </summary>
        [Test]
        public void ArrearsTypeIndTest()
        {
            // TODO unit test for the property 'ArrearsTypeInd'
        }
        /// <summary>
        /// Test the property 'ConsumerAccountID'
        /// </summary>
        [Test]
        public void ConsumerAccountIDTest()
        {
            // TODO unit test for the property 'ConsumerAccountID'
        }
        /// <summary>
        /// Test the property 'CreditLimitAmt'
        /// </summary>
        [Test]
        public void CreditLimitAmtTest()
        {
            // TODO unit test for the property 'CreditLimitAmt'
        }
        /// <summary>
        /// Test the property 'CurrentBalanceAmt'
        /// </summary>
        [Test]
        public void CurrentBalanceAmtTest()
        {
            // TODO unit test for the property 'CurrentBalanceAmt'
        }
        /// <summary>
        /// Test the property 'DeferredPaymentDate'
        /// </summary>
        [Test]
        public void DeferredPaymentDateTest()
        {
            // TODO unit test for the property 'DeferredPaymentDate'
        }
        /// <summary>
        /// Test the property 'DisplayText'
        /// </summary>
        [Test]
        public void DisplayTextTest()
        {
            // TODO unit test for the property 'DisplayText'
        }
        /// <summary>
        /// Test the property 'LastPaymentDate'
        /// </summary>
        [Test]
        public void LastPaymentDateTest()
        {
            // TODO unit test for the property 'LastPaymentDate'
        }
        /// <summary>
        /// Test the property 'MonthlyInstalmentAmt'
        /// </summary>
        [Test]
        public void MonthlyInstalmentAmtTest()
        {
            // TODO unit test for the property 'MonthlyInstalmentAmt'
        }
        /// <summary>
        /// Test the property 'StatusCodeDesc'
        /// </summary>
        [Test]
        public void StatusCodeDescTest()
        {
            // TODO unit test for the property 'StatusCodeDesc'
        }
        /// <summary>
        /// Test the property 'SubAccountNo'
        /// </summary>
        [Test]
        public void SubAccountNoTest()
        {
            // TODO unit test for the property 'SubAccountNo'
        }
        /// <summary>
        /// Test the property 'SubscriberID'
        /// </summary>
        [Test]
        public void SubscriberIDTest()
        {
            // TODO unit test for the property 'SubscriberID'
        }
        /// <summary>
        /// Test the property 'SubscriberName'
        /// </summary>
        [Test]
        public void SubscriberNameTest()
        {
            // TODO unit test for the property 'SubscriberName'
        }
        /// <summary>
        /// Test the property 'ThirdPartyName'
        /// </summary>
        [Test]
        public void ThirdPartyNameTest()
        {
            // TODO unit test for the property 'ThirdPartyName'
        }

    }

}
