/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarisIT.Api.Api;
using MarisIT.Api.Model;
using MarisIT.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarisIT.Api.Test
{
    /// <summary>
    ///  Class for testing XdsConfirmedLinkages
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class XdsConfirmedLinkagesTests
    {
        // TODO uncomment below to declare an instance variable for XdsConfirmedLinkages
        //private XdsConfirmedLinkages instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of XdsConfirmedLinkages
            //instance = new XdsConfirmedLinkages();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of XdsConfirmedLinkages
        /// </summary>
        [Test]
        public void XdsConfirmedLinkagesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" XdsConfirmedLinkages
            //Assert.IsInstanceOf(typeof(XdsConfirmedLinkages), instance);
        }


        /// <summary>
        /// Test the property 'ConfirmedLinkage'
        /// </summary>
        [Test]
        public void ConfirmedLinkageTest()
        {
            // TODO unit test for the property 'ConfirmedLinkage'
        }

    }

}
