/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarisIT.Api.Api;
using MarisIT.Api.Model;
using MarisIT.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarisIT.Api.Test
{
    /// <summary>
    ///  Class for testing XdsMarketPrices
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class XdsMarketPricesTests
    {
        // TODO uncomment below to declare an instance variable for XdsMarketPrices
        //private XdsMarketPrices instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of XdsMarketPrices
            //instance = new XdsMarketPrices();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of XdsMarketPrices
        /// </summary>
        [Test]
        public void XdsMarketPricesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" XdsMarketPrices
            //Assert.IsInstanceOf(typeof(XdsMarketPrices), instance);
        }


        /// <summary>
        /// Test the property 'PriceNew'
        /// </summary>
        [Test]
        public void PriceNewTest()
        {
            // TODO unit test for the property 'PriceNew'
        }
        /// <summary>
        /// Test the property 'PriceTrade'
        /// </summary>
        [Test]
        public void PriceTradeTest()
        {
            // TODO unit test for the property 'PriceTrade'
        }
        /// <summary>
        /// Test the property 'PriceRetail'
        /// </summary>
        [Test]
        public void PriceRetailTest()
        {
            // TODO unit test for the property 'PriceRetail'
        }
        /// <summary>
        /// Test the property 'PriceMarket'
        /// </summary>
        [Test]
        public void PriceMarketTest()
        {
            // TODO unit test for the property 'PriceMarket'
        }
        /// <summary>
        /// Test the property 'PriceHigh'
        /// </summary>
        [Test]
        public void PriceHighTest()
        {
            // TODO unit test for the property 'PriceHigh'
        }
        /// <summary>
        /// Test the property 'PriceLow'
        /// </summary>
        [Test]
        public void PriceLowTest()
        {
            // TODO unit test for the property 'PriceLow'
        }
        /// <summary>
        /// Test the property 'MarketStats'
        /// </summary>
        [Test]
        public void MarketStatsTest()
        {
            // TODO unit test for the property 'MarketStats'
        }

    }

}
