/*
 * MarisIT API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v6
 * Contact: development@marisit.co.za
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarisIT.Api.Api;
using MarisIT.Api.Model;
using MarisIT.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarisIT.Api.Test
{
    /// <summary>
    ///  Class for testing XdsSubscriberInputDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class XdsSubscriberInputDetailsTests
    {
        // TODO uncomment below to declare an instance variable for XdsSubscriberInputDetails
        //private XdsSubscriberInputDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of XdsSubscriberInputDetails
            //instance = new XdsSubscriberInputDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of XdsSubscriberInputDetails
        /// </summary>
        [Test]
        public void XdsSubscriberInputDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" XdsSubscriberInputDetails
            //Assert.IsInstanceOf(typeof(XdsSubscriberInputDetails), instance);
        }


        /// <summary>
        /// Test the property 'AccountNo'
        /// </summary>
        [Test]
        public void AccountNoTest()
        {
            // TODO unit test for the property 'AccountNo'
        }
        /// <summary>
        /// Test the property 'AccountType'
        /// </summary>
        [Test]
        public void AccountTypeTest()
        {
            // TODO unit test for the property 'AccountType'
        }
        /// <summary>
        /// Test the property 'BankName'
        /// </summary>
        [Test]
        public void BankNameTest()
        {
            // TODO unit test for the property 'BankName'
        }
        /// <summary>
        /// Test the property 'BranchCode'
        /// </summary>
        [Test]
        public void BranchCodeTest()
        {
            // TODO unit test for the property 'BranchCode'
        }
        /// <summary>
        /// Test the property 'EnquiryStatus'
        /// </summary>
        [Test]
        public void EnquiryStatusTest()
        {
            // TODO unit test for the property 'EnquiryStatus'
        }
        /// <summary>
        /// Test the property 'ExternalRef'
        /// </summary>
        [Test]
        public void ExternalRefTest()
        {
            // TODO unit test for the property 'ExternalRef'
        }
        /// <summary>
        /// Test the property 'ReferenceNo'
        /// </summary>
        [Test]
        public void ReferenceNoTest()
        {
            // TODO unit test for the property 'ReferenceNo'
        }
        /// <summary>
        /// Test the property 'XdsRefNo'
        /// </summary>
        [Test]
        public void XdsRefNoTest()
        {
            // TODO unit test for the property 'XdsRefNo'
        }
        /// <summary>
        /// Test the property 'EnquiryDate'
        /// </summary>
        [Test]
        public void EnquiryDateTest()
        {
            // TODO unit test for the property 'EnquiryDate'
        }
        /// <summary>
        /// Test the property 'EnquiryType'
        /// </summary>
        [Test]
        public void EnquiryTypeTest()
        {
            // TODO unit test for the property 'EnquiryType'
        }
        /// <summary>
        /// Test the property 'SubscriberName'
        /// </summary>
        [Test]
        public void SubscriberNameTest()
        {
            // TODO unit test for the property 'SubscriberName'
        }
        /// <summary>
        /// Test the property 'SubscriberUsername'
        /// </summary>
        [Test]
        public void SubscriberUsernameTest()
        {
            // TODO unit test for the property 'SubscriberUsername'
        }
        /// <summary>
        /// Test the property 'EnquiryInput'
        /// </summary>
        [Test]
        public void EnquiryInputTest()
        {
            // TODO unit test for the property 'EnquiryInput'
        }
        /// <summary>
        /// Test the property 'TrustNumber'
        /// </summary>
        [Test]
        public void TrustNumberTest()
        {
            // TODO unit test for the property 'TrustNumber'
        }
        /// <summary>
        /// Test the property 'PrebuiltPackage'
        /// </summary>
        [Test]
        public void PrebuiltPackageTest()
        {
            // TODO unit test for the property 'PrebuiltPackage'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'RegistrationNumber'
        /// </summary>
        [Test]
        public void RegistrationNumberTest()
        {
            // TODO unit test for the property 'RegistrationNumber'
        }
        /// <summary>
        /// Test the property 'BusinessName'
        /// </summary>
        [Test]
        public void BusinessNameTest()
        {
            // TODO unit test for the property 'BusinessName'
        }
        /// <summary>
        /// Test the property 'VatNumber'
        /// </summary>
        [Test]
        public void VatNumberTest()
        {
            // TODO unit test for the property 'VatNumber'
        }
        /// <summary>
        /// Test the property 'IdNumber'
        /// </summary>
        [Test]
        public void IdNumberTest()
        {
            // TODO unit test for the property 'IdNumber'
        }
        /// <summary>
        /// Test the property 'NpoNumber'
        /// </summary>
        [Test]
        public void NpoNumberTest()
        {
            // TODO unit test for the property 'NpoNumber'
        }
        /// <summary>
        /// Test the property 'EnquiryReference'
        /// </summary>
        [Test]
        public void EnquiryReferenceTest()
        {
            // TODO unit test for the property 'EnquiryReference'
        }
        /// <summary>
        /// Test the property 'ExternalReference'
        /// </summary>
        [Test]
        public void ExternalReferenceTest()
        {
            // TODO unit test for the property 'ExternalReference'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Test]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'YourReference'
        /// </summary>
        [Test]
        public void YourReferenceTest()
        {
            // TODO unit test for the property 'YourReference'
        }
        /// <summary>
        /// Test the property 'LegalEntity'
        /// </summary>
        [Test]
        public void LegalEntityTest()
        {
            // TODO unit test for the property 'LegalEntity'
        }
        /// <summary>
        /// Test the property 'VoucherCode'
        /// </summary>
        [Test]
        public void VoucherCodeTest()
        {
            // TODO unit test for the property 'VoucherCode'
        }
        /// <summary>
        /// Test the property 'EnquiryReason'
        /// </summary>
        [Test]
        public void EnquiryReasonTest()
        {
            // TODO unit test for the property 'EnquiryReason'
        }
        /// <summary>
        /// Test the property 'IdNo'
        /// </summary>
        [Test]
        public void IdNoTest()
        {
            // TODO unit test for the property 'IdNo'
        }
        /// <summary>
        /// Test the property 'Surname'
        /// </summary>
        [Test]
        public void SurnameTest()
        {
            // TODO unit test for the property 'Surname'
        }
        /// <summary>
        /// Test the property 'Initials'
        /// </summary>
        [Test]
        public void InitialsTest()
        {
            // TODO unit test for the property 'Initials'
        }
        /// <summary>
        /// Test the property 'EmailAddress'
        /// </summary>
        [Test]
        public void EmailAddressTest()
        {
            // TODO unit test for the property 'EmailAddress'
        }
        /// <summary>
        /// Test the property 'ContactNumber'
        /// </summary>
        [Test]
        public void ContactNumberTest()
        {
            // TODO unit test for the property 'ContactNumber'
        }
        /// <summary>
        /// Test the property 'RequesterFirstName'
        /// </summary>
        [Test]
        public void RequesterFirstNameTest()
        {
            // TODO unit test for the property 'RequesterFirstName'
        }
        /// <summary>
        /// Test the property 'RequesterSurname'
        /// </summary>
        [Test]
        public void RequesterSurnameTest()
        {
            // TODO unit test for the property 'RequesterSurname'
        }
        /// <summary>
        /// Test the property 'RefNumber'
        /// </summary>
        [Test]
        public void RefNumberTest()
        {
            // TODO unit test for the property 'RefNumber'
        }

    }

}
